const quoteJsonName = "quote-obj",
    portalId = '5020112',
    schoolProgramListTable = '5266066',
    schoolPriceListTable = '5285248',
    accommodationPriceListTable = '5285248',
    schoolMarketPriceListTable = '5311767',
    startDateTable = '5315512',
    paymentTable = '93639180',
    fGuid = '16975c08-0411-4537-b12f-10487a4ae8d4',
    studentGuid = 'be072370-2cc2-46ca-a317-aca7db1062f6',
    fEnrollGuid = '322dd72c-0d30-4e45-ba37-f941d32e6bfa',
    accommGuid = '8b10e07b-92c7-4db3-bfe3-99d26727e8bc',
    paymentGuid = '98c25281-3d9f-4cc4-8da9-3213ae72cf33',
    promoTable = '5591565',
    schoolName = 'Language Schools',
    pageUri = "www.ilsc.com/online-application",
    pageName = "ILSC Price Quote",
    consentAgreeTxt = "I agree to allow ILSC to store and process my personal data.",
    privacyAgreementLabel = 'I agree to receive other communications from ILSC Language Schools and Greystone College.',
    privacyAgreementPreHtml = '<p>ILSC Language Schools and Greystone College are committed to protecting and respecting your privacy, and we&apos;ll only use your personal information to administer your account and to provide the products and services you requested from us.  From time to time, we would like to contact you about our products and services, as well as other content that may be of interest to you.  If you consent to us contacting you for this purpose, please tick below:</p>',
    privacyAgreementPostHtml = '<p>You can unsubscribe from these communications at any time.  For more information on how to unsubscribe, our privacy practices, and how we are committed to protecting and respecting your privacy, please review our <a href="https://www.ilsc.com/privacy-policy" target="_blank">Privacy Policy</a>.</p>',
    paymentMessage = '<p>Congratulations! We have received your application. One of our agents is processing your request and contacting your chosen school to check availability.</p><p>In the meantime, please pay a depost of <span id="depoist-amt">CAD 100</span> by credit card so that we can process your registration faster. Whilst this payment does not guarantee your place or complete your enrolment, it does ensure that your application is handled with the utmost prioirty.</p><p>Your placement can be guaranteed when the full amount has been paid and the school has confirmed availability. We will contact you directly to confirm this.</p>',
    apiUrl = 'https://api.hubapi.com/cms/v3/hubdb/tables/',
    homestayNote = 'A high season supplement of $40 per week applies to all Canadian homestay accommodations based on the dates of your stay for weeks from the night of May 31 to the night of August 31, 2025';
