const quoteJsonName = "quote-obj",
        portalId = '5020112',
        schoolProgramListTable = '5475402',
        schoolPriceListTable = '6973607',
        accommodationPriceListTable = '6973607',
        schoolMarketPriceListTable = '7113991',
        accommodationTable = '5481137',
        accommodationPartnersTable = '2642568',
        paymentTable = '93639180',
        startDateTable = '5470828',
        fGuid = '69a15b8e-0008-4ab1-9e36-6d5be0b25b80',
        studentGuid = 'ca0b85c6-b80e-49f0-b7c5-b3c0c915657e',
        fEnrollGuid = '5367ca75-1afe-403f-8153-b797d603df8c',
        accommGuid = 'd6470fd4-c774-4370-8a6f-94fb4a4aad22',
        paymentGuid = 'e1b6d2aa-3c0e-43ec-ade4-e04dd300f5b4',
        promoTable = '5591565',
        schoolName = 'ELS',
        pageUri = "www.els.edu/online-application",
        pageName = "ELS Price Quote",
        consentAgreeTxt = "I agree to allow ELS to store and process my personal data.",
        privacyAgreementLabel = 'I agree to receive other communications from ELS Language Centers<sup>*</sup>',
        privacyAgreementPreHtml = '<p>ELS Language Centers is committed to protecting and respecting your privacy, and we&apos;ll only use your personal information to administer your account and to provide the products and services you requested from us. From time to time, we would like to contact you about our products and services, as well as other content that may be of interest to you. If you consent to us contacting you for this purpose, please tick below:</p>',
        privacyAgreementPostHtml = '<p>You can unsubscribe from these communications at any time. For more information on how to unsubscribe, our privacy practices, and how we are committed to protecting and respecting your privacy, please review our <a href="https://link.edgepilot.com/s/3d7d536c/VQL0vSd0OUKqrlfKfVk69Q?u=https://www.els.edu/privacy-policy" target="_blank">Privacy Policy</a>.</p><p>By clicking "Next" below, you consent to allow ELS Language Centers to store and process the personal information submitted above to provide you the content requested.</p>',
        paymentRedirectUrl = '/price-quote/els/thank-you',
        payUrl = 'https://quotingtool.azurewebsites.net/api/DepositCheckout',
        exceptionText = "From Nov 7, 2022 (session 12) to March 24, 2023 (Session 3), we charge regular price for the Full-Time Morning schedule. The price will be $440 (1-11 weeks) / $420 (12-23 weeks) / $400 (24+ weeks) per week. Please consult with your advisor or agency.",
        preFinancialHtml = "<div class='footnote'><h5>FINANCIAL AND HEALTH STATEMENT/INFORMATION RELEASE</h5><p>I understand that my expenses (excluding personal miscellaneous expenses) per session while studying at ELS Language Centers will be as indicated in the <a href='https://www.els.edu/how-to-apply/tuition-fees' target='_blank'>Prices and Dates</a>. I agree to accept full responsibility for these expenses. I have also read and understand the ELS cancellation and refund policy. I agree to accept full responsibility for my actions while participating in the Program and any related activities (including excursions and/or internships) and agree to assume all risk of harm arising from my participation, unless caused by ELS' negligence.</p><p>I hereby agree that ELS shall have the right, in its sole discretion, to terminate my attendance in any ELS program of study and to insist that I return to my country of origin within 24 hours of such termination by ELS. By his or her signature below, my parent or guardian agrees to ensure that any minor under the age of 18 enrolled hereunder shall be returned to his or her country of origin within 24 hours of notification from ELS that the student's attendance in an ELS program has been terminated.</p><p>In case of illness and/or injury, permission is granted to any appropriate medical center to examine or treat and make necessary referrals to outside physicians as indicated. Permission is also granted to release information regarding my health to other designated individuals. I authorize ELS Language Centers to release information regarding my studies to my guardian or sponsoring agency. I further authorize ELS Language Centers to release my ELS academic records to any colleges or universities to which I apply. I understand that I have the right to review my official ELS student record.</p><p>I hereby grant ELS Language Centers and its subsidiaries, associated companies and licensees, permission to photograph, record and videotape me while attending ELS Language Centers or activities conducted by ELS Language Centers. I understand that ELS Language Centers will own the still photographs and/or video footage in which I appear, and have the unrestricted right to publish such photographs and use such video in any ELS Language Centers sales literature, on the ELS Language Centers Web site and in any other ELS Language Centers material, and shall have the right to license others to do the same. I further understand that this grant is intended to be worldwide in scope and to apply to all media now existing or hereafter developed.</p><p>I understand that ELS shall not release my information, except as described above, to anyone or any organization or entity, outside of its subsidiaries and associated companies and licensees, without my written consent.</p>",
        postFinancialHtml = "<div class='footnote'>By submitting this form by clicking the confirmation button below, you acknowledge that you have read and agree to the <a href='https://www.els.edu/terms-of-use' target='_blank'>Terms of Use</a>,<a href='https://www.els.edu/privacy-policy' target='_blank'>Privacy Policy</a>,<a href='https://www.els.edu/hubfs/ELS/pdf/documents/ELS_Cancellation_Policy.pdf' target='_blank'>Cancellation & Refund Policy</a> and <a href='https://www.els.edu/admissions/tuition-fees' target='_blank'>Prices & Dates addendum</a></div>",
        depositTotal = 350,
        serviceFeePercent = .045,
        serviceFeeMessage = '+4.5% service fee',
    apiUrl = 'https://api.hubapi.com/cms/v3/hubdb/tables/',
    homestayNote = '';