//initialize quote json object
let CountryOrigin="",
    TargetCurrency="",
    SchoolName="none",
    marketPriceCode="none",
    ProgramSchoolName="none",
    CampusName_1="none",
    CampusName_2="none",
    CampusName_3="none",
    CampusCountry_1="none",
    CampusCountry_2="none",
    CampusCountry_3="none",
    CampusCurrency_1="",
    CampusCurrency_2="",
    CampusCurrency_3="",
    ShowCurrency_1="",
    ShowCurrency_2="",
    ShowCurrency_3="",
    PromoCode_1="none",
    PromoCode_2="none",
    PromoCode_3="none",
    PromoAutoName_1="none",
    PromoAutoName_2="none",
    PromoAutoName_3="none",
    PromoDescription_1="none",
    PromoDescription_2="none",
    PromoDescription_3="none",
    PromoCategory_1="none",
    PromoCategory_2="none",
    PromoCategory_3="none",
    promoDiscountType_1="none",
    promoDiscountType_2="none",
    promoDiscountType_3="none",
    promoType_1="none",
    promoType_2="none",
    promoType_3="none",
    Category_1="",
    Category_2="",
    Category_3="",
    ProgramName_1="none",
    ProgramName_2="none",
    ProgramName_3="none",
    ScheduleName_1="none",
    ScheduleName_2="none",
    ScheduleName_3="none",
    ScheduleDescription_1="none",
    ScheduleDescription_2="none",
    ScheduleDescription_3="none",
    RegistrationDescription_1="none",
    RegistrationDescription_2="none",
    RegistrationDescription_3="none",
    AdditionalFeeDescription_1="none",
    AdditionalFeeDescription_2="none",
    AdditionalFeeDescription_3="none",
    AdditionalItemName_1="none",
    AdditionalItemName_2="none",
    AdditionalItemName_3="none",
    StartDate_1="",
    StartDate_2="",
    StartDate_3="",
    EndDate_1="",
    EndDate_2="",
    EndDate_3="",
    Duration_1="",
    Duration_2="",
    Duration_3="",
    ProgramNote_1="none",
    ProgramNote_2="none",
    ProgramNote_3="none",
    LengthStay_1="0",
    LengthStay_2="0",
    LengthStay_3="0",
    CheckIn_1="1-1-1999",
    CheckIn_2="1-1-1999",
    CheckIn_3="1-1-1999",
    AccommodationOption_1="none",
    AccommodationOption_2="none",
    AccommodationOption_3="none",
    AccommodationNote_1="none",
    AccommodationNote_2="none",
    AccommodationNote_3="none",
    AccommodationNotePlain_1="none",
    AccommodationNotePlain_2="none",
    AccommodationNotePlain_3="none",
    AirporTransfer_1="none",
    AirporTransfer_2="none",
    AirporTransfer_3="none"
    
let quote_obj={   
    "country_origin":CountryOrigin,
    "country_origin_currency": TargetCurrency,
    "school_name":SchoolName,
    "school_id":0,
    "program_school_name":ProgramSchoolName,
    "quote_array":[
            {
               
                "quote_enabled":true,
                "quote_var":1,
                "campus":CampusName_1,
                "campus_id":0,
                "campus_country":CampusCountry_1,
                "campus_currency": CampusCurrency_1,
                "show_currency": ShowCurrency_1,
                "market_price_code":marketPriceCode,
                "market_price_id":0,
                "program":
                    {
                        "category": Category_1,
                        "option_program": ProgramName_1,
                        "option_schedule": ScheduleName_1,
                        "option_schedule_description": ScheduleDescription_1,
                        "start_date": StartDate_1,
                        "end_date": EndDate_1,
                        "duration": Duration_1,
                        "program_total_price":0,
                        "program_total_standard_price":0,
                        "registration_fee":0,
                        "registration_description":RegistrationDescription_1,
                        "material_fee":0,
                        "additional_fee":0,
                        "additional_fee_description":AdditionalFeeDescription_1,
                        "additional_item_name":AdditionalItemName_1,
                        "program_id":0,
                        "group_id":0,
                        "program_note":ProgramNote_1
                    }
                ,
                "accommodation":
                    {
                      "accommodation_enable":false,
                      "accommodation_note":AccommodationNote_1,
                      "accommodation_note_plain":AccommodationNotePlain_1,
                      "length_of_stay":LengthStay_1,
                      "check_in_date":CheckIn_1,
                      "option_accommodation":AccommodationOption_1,
                      "option_accommodation_id":0,
                      "option_airport_transfer":AirporTransfer_1,
                      "option_airport_id":0,
                      "airport_transfer_total_price":0,
                      "accommodation_total_price":0,
                      "placement_fee":0,
                      "cleaning_fee":0,
                      "is_under_age":false,
                      "family_enable":false,
                      "family_additional_child":0,
                      "family_additional_adult":0,
                      "family_additional_child_total_price":0,
                      "family_additional_adult_total_price":0
                    }
                ,
                "promo":{
                  "promo_code_enabled":false,
                  "promo_code":PromoCode_1,
                  "promo_code_name": PromoAutoName_1,
                  "promo_code_description": PromoDescription_1,
                  "promo_code_category": PromoCategory_1,
                  "promo_code_discount_type": promoDiscountType_1,
                  "promo_code_type": promoType_1,
                  "promo_code_value": 0,
                  "promo_auto_enabled":false,
                  "promo_auto_code":PromoCode_1,
                  "promo_auto_code_name": PromoAutoName_1,
                  "promo_auto_description": PromoDescription_1,
                  "promo_auto_category": PromoCategory_1,
                  "promo_auto_discount_type": promoDiscountType_1,
                  "promo_auto_type": promoType_1,
                  "promo_auto_value": 0
                },
                "quote_total_price":0,
            },
            {
                "quote_enabled":false,
                "quote_var":2,
                "campus":CampusName_2,
                "campus_id":0,
                "campus_country":CampusCountry_2,
                "campus_currency": CampusCurrency_2,
                "show_currency": ShowCurrency_2,
                "market_price_code":marketPriceCode,
                "market_price_id":0,
                "program":
                    {
                        "category": Category_2,
                        "option_program": ProgramName_2,
                        "option_schedule": ScheduleName_2,
                        "option_schedule_description": ScheduleDescription_2,
                        "start_date": StartDate_2,
                        "end_date": EndDate_1,
                        "duration": Duration_2,
                        "program_total_price":0,
                        "program_total_standard_price":0,
                        "registration_fee":0,
                        "registration_description":RegistrationDescription_2,
                        "material_fee":0,
                        "additional_fee":0,
                        "additional_fee_description":AdditionalFeeDescription_2,
                        "additional_item_name":AdditionalItemName_2,
                        "program_id":0,
                        "group_id":0,
                        "program_note":ProgramNote_2
                    }
                ,
                "accommodation":
                    {
                      "accommodation_enable":false,
                      "accommodation_note":AccommodationNote_2,
                      "accommodation_note_plain":AccommodationNotePlain_2,
                      "length_of_stay":LengthStay_2,
                      "check_in_date":CheckIn_2,
                      "option_accommodation":AccommodationOption_2,
                      "option_accommodation_id":0,
                      "option_airport_transfer":AirporTransfer_2,
                      "option_airport_id":0,
                      "airport_transfer_total_price":0,
                      "accommodation_total_price":0,
                      "placement_fee":0,
                      "cleaning_fee":0,
                      "is_under_age":false,
                      "family_enable":false,
                      "family_additional_child":0,
                      "family_additional_adult":0,
                      "family_additional_child_total_price":0,
                      "family_additional_adult_total_price":0
                    }
                ,
                "promo":{
                  "promo_code_enabled":false,
                  "promo_code":PromoCode_2,
                  "promo_code_name": PromoAutoName_2,
                  "promo_code_description": PromoDescription_2,
                  "promo_code_category": PromoCategory_2,
                  "promo_code_discount_type": promoDiscountType_2,
                  "promo_code_type": promoType_2,
                  "promo_code_value": 0,
                  "promo_auto_enabled":false,
                  "promo_auto_code":PromoCode_2,
                  "promo_auto_code_name": PromoAutoName_2,
                  "promo_auto_description": PromoDescription_2,
                  "promo_auto_category": PromoCategory_2,
                  "promo_auto_discount_type": promoDiscountType_2,
                  "promo_auto_type": promoType_2,
                  "promo_auto_value": 0
                },
                "quote_total_price":0      
            },
            {
                "quote_enabled":false,
                "quote_var":3,
                "campus":CampusName_3,
                "campus_id":0,
                "campus_country":CampusCountry_3,
                "campus_currency": CampusCurrency_3,
                "show_currency": ShowCurrency_3,
                "market_price_code":marketPriceCode,
                "market_price_id":0,
                "program":
                    {
                        "category": Category_3,
                        "option_program": ProgramName_3,
                        "option_schedule": ScheduleName_3,
                        "option_schedule_description": ScheduleDescription_3,
                        "start_date": StartDate_3,
                        "end_date": EndDate_1,
                        "duration": Duration_3,
                        "program_total_price":0,
                        "program_total_standard_price":0,
                        "registration_fee":0,
                        "registration_description":RegistrationDescription_3,
                        "material_fee":0,
                        "additional_fee":0,
                        "additional_fee_description":AdditionalFeeDescription_3,
                        "additional_item_name":AdditionalItemName_3,
                        "program_id":0,
                        "group_id":0,
                        "program_note":ProgramNote_3
                    }
                ,
                "accommodation":
                    {
                      "accommodation_enable":false,
                      "accommodation_note":AccommodationNote_3,
                      "accommodation_note_plain":AccommodationNotePlain_3,
                      "length_of_stay":LengthStay_3,
                      "check_in_date":CheckIn_3,
                      "option_accommodation":AccommodationOption_3,
                      "option_accommodation_id":0,
                      "option_airport_transfer":AirporTransfer_3,
                      "option_airport_id":0,
                      "airport_transfer_total_price":0,
                      "accommodation_total_price":0,
                      "placement_fee":0,
                      "cleaning_fee":0,
                      "is_under_age":false,
                      "family_enable":false,
                      "family_additional_child":0,
                      "family_additional_adult":0,
                      "family_additional_child_total_price":0,
                      "family_additional_adult_total_price":0
                    }
                ,
                "promo":{
                  "promo_code_enabled":false,
                  "promo_code":PromoCode_3,
                  "promo_code_name": PromoAutoName_3,
                  "promo_code_description": PromoDescription_3,
                  "promo_code_category": PromoCategory_3,
                  "promo_code_discount_type": promoDiscountType_3,
                  "promo_code_type": promoType_3,
                  "promo_code_value": 0,
                  "promo_auto_enabled":false,
                  "promo_auto_code":PromoCode_3,
                  "promo_auto_code_name": PromoAutoName_3,
                  "promo_auto_description": PromoDescription_3,
                  "promo_auto_category": PromoCategory_3,
                  "promo_auto_discount_type": promoDiscountType_3,
                  "promo_auto_type": promoType_3,
                  "promo_auto_value": 0
                },
                "quote_total_price":0       
            }
        ]
    
    };

const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
    "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
    "Congo",
  "Cook Islands",
  "Costa Rica",
    "Cote d&#39;Ivoire",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czech Republic",
    "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
    "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern and Antarctic Lands",
  "Gabon",
  "Gambia ",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands ",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar (Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
    "North Korea",
    "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Reunion",
  "Saint Barthélemy",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan ",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands ",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates ",
  "United Kingdom",
  "United States Minor Outlying Islands ",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "British Virgin Islands",
  "U.S. Virgin Islands",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

const setQuoteStorage = function(){
    localStorage.setItem("quote-obj", JSON.stringify(quote_obj));
}

const checkCookieRedirect = function(){
  
  //let isCookie = getInitCookie('__hstc');
  
  if(!navigator.cookieEnabled){
     window.location.href = '/quote/country-school-selection';
  }

}
const enableCampus = function(){
  
  let quoteObj = JSON.parse(localStorage.getItem("region-code")),
      usSubStr = 'US',
      caSubStr = 'CA',
      auSubStr = 'AU',
      olSubStr = 'OL',
      idSubStr = 'IND',
      school = $('input[name=school_selection]').val(),
      schoolStr = '',
      codeArray = [];
  
  if(school == 'Greystone College'){
    schoolStr = 'GC';
  }else if(school == 'Language Schools'){
    schoolStr = 'LS';       
  }else if(school == 'ELS'){
    schoolStr = 'ELS'
  }
      
  for(let i = 0; i < quoteObj.length; i++){
    codeArray.push(
      quoteObj[i].region_code
    );  
  } 
  let codeArrayFilter = codeArray.filter(a => a.includes(schoolStr));
  let caResult = codeArrayFilter.filter(a => a.includes(caSubStr)),
      auResult = codeArrayFilter.filter(a => a.includes(auSubStr)),
      olResult = codeArrayFilter.filter(a => a.includes(olSubStr)),
      idResult = codeArrayFilter.filter(a => a.includes(idSubStr)),
      usResult = codeArrayFilter.filter(a => a.includes(usSubStr));
  
  if(caResult.length == 0){
    $('#campus-select-Canada').remove();
  }
  if(auResult == 0){
    $('#campus-select-Australia').remove();
  }
  if(olResult == 0){
    $('#campus-select-Online').remove();
  }
  if(idResult == 0){
    $('#campus-select-India').remove();
  }
  if(usResult == 0){
    $('#campus-select-USA').remove();
  }
  
}

const printNationalityForm = function(){
  let optionHtml;

  for (let optionList in countryList) {
    optionValue = countryList[optionList];
    optionHtml += "<option value='" + optionValue + "'>" + optionValue + "</option>";
  }
  $('select#nationality-select').append(optionHtml);
};
$(document).ready(function () {
  enableCampus();
  setQuoteStorage();
  printNationalityForm();
  
  let grayC = '#6c757d',
      blackC = '#212529',
      selectElement = 'select#nationality-select';

  $(selectElement).css('color',grayC);
   $(selectElement).change(function() {
      var current = $(selectElement).val();
      if (current != 'null') {
          $(selectElement).css('color',blackC);
      } else {
          $(selectElement).css('color',grayC);
      }
   }); 
});
document.addEventListener("DOMContentLoaded", () => {
  checkCookieRedirect();
});
 